// electron-builder configuration. One file for both distribution modes so the
// personal and release builds cannot drift apart: everything below is shared,
// and only the `release` branch adds real signing, notarization, and the
// GitHub Releases feed. The mode comes from the same environment variable
// scripts/write-distribution-metadata.mjs reads, so the packaged metadata and
// the signing posture always agree (T39, SPEC §6 Packaging).
//
//   npm run package:mac            personal: ad-hoc signed, no updater
//   ATTN_DISTRIBUTION_MODE=release ATTN_RELEASE_FEED=owner/repo npm run release:mac
//                                  release: Developer ID + notarization, feed declared
//
// A release build without credentials fails inside electron-builder (no
// identity, no notarytool login) rather than falling back to personal.

/** biome-ignore-all lint/suspicious/noTemplateCurlyInString: `${arch}` and friends are electron-builder macros, expanded at package time. */

const mode = process.env.ATTN_DISTRIBUTION_MODE ?? 'personal'
if (mode !== 'personal' && mode !== 'release') throw new Error(`unknown ATTN_DISTRIBUTION_MODE "${mode}"`)
const release = mode === 'release'

function releaseFeed() {
  const [owner, repo] = (process.env.ATTN_RELEASE_FEED ?? '').split('/')
  if (!owner || !repo) throw new Error('release packaging requires ATTN_RELEASE_FEED="owner/repo"')
  return { owner, repo }
}

/** @type {import('electron-builder').Configuration} */
const config = {
  appId: 'com.useattn.attn',
  productName: 'Attn',

  directories: {
    buildResources: 'resources',
    output: 'dist'
  },

  files: [
    'out/**/*',
    'package.json',
    'LICENSE',
    'resources/icon.png',
    'resources/icon-matcha.png',
    'resources/icon-mist.png',
    'resources/icon-linen.png',
    'resources/icon-dusk.png',
    'resources/menuBarTemplate.png',
    'resources/tray.png',
    '!node_modules/better-sqlite3/{build,deps,src}/**/*'
  ],

  asar: true,

  // T39: the distribution metadata generated by scripts/write-distribution-metadata.mjs
  // lands beside app.asar. Personal is the default; only an explicit release
  // build declares an update feed, and the runtime treats anything missing or
  // malformed as personal (no updater).
  extraResources: [{ from: 'dist-resources/distribution.json', to: 'distribution.json' }],

  // better-sqlite3 ships Node-API prebuilds, which are ABI-stable across Electron
  // versions — the per-arch rebuild only produces a build/ tree the file patterns
  // above then drop. A future non-N-API dependency fails loudly instead of
  // silently: postinstall's in-Electron smoke test catches it, and
  // scripts/verify-package.mjs asserts the one expected prebuild is packaged.
  npmRebuild: false,

  artifactName: '${productName}-${version}-${os}-${arch}.${ext}',

  // Release builds write latest.yml / latest-mac.yml for the rolling feed. The
  // workflow stamps the target and minimum migratable schemas before upload,
  // so the CLI runs with --publish never; personal builds declare no feed.
  ...(release ? { publish: { provider: 'github', ...releaseFeed() } } : {}),

  mac: {
    category: 'public.app-category.productivity',
    icon: 'icon.icns',
    target: ['dmg', 'zip'],
    files: ['!node_modules/better-sqlite3/prebuilds/!(darwin-${arch}.node)'],
    asarUnpack: ['node_modules/better-sqlite3/prebuilds/darwin-${arch}.node'],
    ...(release
      ? {
          // Developer ID Application from CSC_LINK / CSC_KEY_PASSWORD; the
          // hardened runtime and these entitlements are what notarization
          // requires of an Electron app. Notarization reads APPLE_ID,
          // APPLE_APP_SPECIFIC_PASSWORD, and APPLE_TEAM_ID (or the App Store
          // Connect API key trio) and staples the ticket to the .app.
          hardenedRuntime: true,
          entitlements: 'resources/entitlements.mac.plist',
          entitlementsInherit: 'resources/entitlements.mac.plist',
          notarize: true
        }
      : {
          // Ad-hoc signature: runs on the building Mac, never notarized.
          identity: '-',
          hardenedRuntime: false
        })
  },

  win: {
    icon: 'icon.ico',
    target: ['nsis'],
    files: ['!node_modules/better-sqlite3/prebuilds/!(win32-${arch}.node)'],
    asarUnpack: ['node_modules/better-sqlite3/prebuilds/win32-${arch}.node']
    // Release signing needs no config: electron-builder signs with the PFX in
    // WIN_CSC_LINK / WIN_CSC_KEY_PASSWORD when they are set, and the release
    // verifier requires the resulting Authenticode signature.
  },

  // Linux is not a shipping target (SPEC: macOS + Windows). It exists so
  // `npm run package:dir` is a real smoke test on a Linux dev box or CI container.
  linux: {
    category: 'Office',
    target: ['dir'],
    files: ['!node_modules/better-sqlite3/prebuilds/!(linux-${arch}.node)'],
    asarUnpack: ['node_modules/better-sqlite3/prebuilds/linux-${arch}.node']
  },

  nsis: {
    oneClick: false,
    allowToChangeInstallationDirectory: true
  }
}

module.exports = config
